// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYpLEb1J_ds5SiO4YVH2j9qrsOXXHggqs',
    appId: '1:183995815463:web:d1841f9dd0a10578fee002',
    messagingSenderId: '183995815463',
    projectId: 'coffee-chat-84cd5',
    authDomain: 'coffee-chat-84cd5.firebaseapp.com',
    storageBucket: 'coffee-chat-84cd5.appspot.com',
    measurementId: 'G-EGN3X42ZDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxsAfLIaFBq-YQcgk_uMo2FIzXmhtMblg',
    appId: '1:183995815463:android:cf1cd6be94b88edefee002',
    messagingSenderId: '183995815463',
    projectId: 'coffee-chat-84cd5',
    storageBucket: 'coffee-chat-84cd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBolAWnGhoNOX-w8EBWIZvW_BQJc4zJuVc',
    appId: '1:183995815463:ios:ff210bb07b268588fee002',
    messagingSenderId: '183995815463',
    projectId: 'coffee-chat-84cd5',
    storageBucket: 'coffee-chat-84cd5.appspot.com',
    androidClientId: '183995815463-il62mf2j1cle6j0b53s9sjjsgjj6nsrt.apps.googleusercontent.com',
    iosClientId: '183995815463-pq1068gcdcce7pbf50foo97bkep6f83e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBolAWnGhoNOX-w8EBWIZvW_BQJc4zJuVc',
    appId: '1:183995815463:ios:ff210bb07b268588fee002',
    messagingSenderId: '183995815463',
    projectId: 'coffee-chat-84cd5',
    storageBucket: 'coffee-chat-84cd5.appspot.com',
    androidClientId: '183995815463-il62mf2j1cle6j0b53s9sjjsgjj6nsrt.apps.googleusercontent.com',
    iosClientId: '183995815463-pq1068gcdcce7pbf50foo97bkep6f83e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppMobile',
  );
}
